In [1]:
import pandas as pd

### 关联性状和基因表达数据

In [4]:
df_phenos = pd.read_csv('../results/phenos_rename_sorted_filled.csv')
df_phenos

,Entry_Treatment_Replicate,Treatment,Replicate,Entry,DTF,CCI,LAI,FS,Fecundity,EntryNumber
0,e1_Dry_1,Dry,1,e1,102.0,21.8,0.103337,0,0.0,1
1,e1_Dry_2,Dry,2,e1,102.0,4.4,0.614793,0,0.0,1
2,e1_Dry_3,Dry,3,e1,102.0,12.6,0.511816,0,0.0,1
3,e1_Wet_1,Wet,1,e1,95.0,24.2,1.600272,0,120.0,1
4,e1_Wet_2,Wet,2,e1,95.0,18.0,0.730042,1,19.0,1
...,...,...,...,...,...,...,...,...,...,...
1315,e220_Dry_2,Dry,2,e220,0.0,5.6,1.424527,0,0.0,220
1316,e220_Dry_3,Dry,3,e220,0.0,37.8,0.817088,0,0.0,220
1317,e220_Wet_1,Wet,1,e220,95.0,22.2,3.609464,1,819.0,220
1318,e220_Wet_2,Wet,2,e220,95.0,8.0,3.586099,0,592.5,220
1319,e220_Wet_3,Wet,3,e220,95.0,42.5,2.542439,1,366.0,220

In [9]:
# 读取rpkm数据
df_rpkm = pd.read_csv('../results/rpkm_T.csv')

In [10]:
df_rpkm

,geneID,Os01g0101700,Os01g0102700,Os01g0105900,Os01g0109300,Os01g0109700,Os01g0118400,Os01g0120300,Os01g0120500,Os01g0128800,...,Os09g0513000,Os09g0514600,Os09g0531100,Os09g0532700,Os09g0534200,Os09g0539100,Os09g0542100,Os09g0553800,Os09g0560400,Os09g0568900
0,e14_Wet_3,33.381458,11.221223,34.355198,9.210123,8.141581,88.536956,7.048557,94.550601,22.762338,...,13.922836,38.340464,18.532924,100.488216,20.048082,107.492056,34.028982,26.622270,21.388518,283.267450
1,e45_Wet_3,66.874474,44.959892,8.739709,2.108689,16.776381,83.468140,12.103431,82.982766,11.844349,...,37.189601,21.945445,50.918102,62.995672,19.125316,94.656415,25.970166,45.714438,24.484866,86.473381
2,e165_Wet_3,94.537539,31.778923,30.269620,4.173346,16.601229,23.599057,3.992355,110.678616,39.850345,...,26.286662,65.148978,33.590998,70.469012,15.140512,74.934531,25.699027,30.158107,0.000000,149.748487
3,e178_Dry_3,59.955689,40.308374,22.853556,0.000000,11.698329,68.596537,12.659755,101.892130,14.866518,...,16.670996,45.908299,13.314628,91.674735,24.005274,69.305053,36.218484,55.784941,15.366176,67.836043
4,e7_Wet_3,82.610842,20.827311,23.616835,0.000000,8.059359,6.444325,4.360858,116.994663,15.363041,...,22.970381,71.162366,36.691518,65.131381,16.538013,117.661022,14.035551,24.706323,21.172515,186.937813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,e6_Wet_1,28.433011,0.000000,19.508270,0.000000,5.547743,26.616103,0.000000,48.320687,3.525102,...,0.000000,0.000000,6.314246,28.530635,17.076167,21.128654,6.441010,22.675802,0.000000,96.510424
1341,e195_Dry_1,13.779743,37.056635,12.605955,3.041524,0.000000,17.198931,2.909618,15.612056,10.250410,...,7.663060,94.960812,12.240516,23.703523,5.517183,6.826511,24.972512,21.979150,7.063281,93.545407
1342,e18_Dry_1,13.959860,28.155757,19.156094,0.000000,2.723796,8.711871,0.000000,47.448371,6.922930,...,7.763226,96.202063,12.400514,24.013356,5.589299,27.662968,6.324733,22.266444,0.000000,94.768156
1343,e167_Wet_1,14.321051,0.000000,6.550577,3.161004,2.794270,44.686390,0.000000,27.042239,7.102051,...,15.928176,65.794101,0.000000,24.634667,5.733914,14.189354,6.488376,0.000000,14.681495,64.813430
1344,zero_ratio,0.973214,0.908482,0.930804,0.819940,0.938244,0.866815,0.805804,0.998512,0.960565,...,0.835565,0.918155,0.944196,0.998512,0.876488,0.993304,0.886161,0.893601,0.805060,0.959821

In [11]:
merged_data = pd.merge(df_phenos, df_rpkm, left_on='Entry_Treatment_Replicate', right_on='geneID')
merged_data = merged_data.drop(columns=['geneID'])
merged_data.to_csv('../results/phenos_rpkm.csv', index=False)

### 缺失值处理

In [12]:
# 数据处理规则: 每三行为一组，如果一组数据中0值数量为1个，取非0值填补缺失值，如果0值数量为2个，取非0的值的平均值填补0值，如果缺失值数量为3个，则保留0值
def fill_zero_values(group):
    # 计算0值的数量
    zero_count = (group == 0).sum()
    # 计算非0值的数量
    non_zero_count = len(group) - zero_count
    # 如果没有0值，直接返回原组
    if non_zero_count == len(group):
        return group
    # 如果有一个0值，取非0的值填补0值
    elif zero_count == 1:
        return group.replace(0, group[group != 0].mean())
    # 如果有两个0值，取非0的值的平均值填补0值
    elif zero_count == 2:
        return group.replace(0, group[group != 0].mean())
    # 如果有三个0值，则保留0值
    else:
        return group
# 读取数据
df = pd.read_csv('../results/phenos_rpkm.csv')
# 按照每三行分组    
grouped = df.groupby(df.index // 3)
# 对每组数据应用填补0值的函数
df_filled = grouped.apply(lambda x: x.apply(fill_zero_values, axis=0))
# 重置索引  
df_filled = df_filled.reset_index(drop=True)
# 保存填补后的数据
df_filled.to_csv('../results/phenos_rpkm_filled.csv', index=False)

### 按性状拆分

In [13]:
# 再次排序，按照Replicate、EntryNumber、Treatment排序
df_filled = pd.read_csv('../results/phenos_rpkm_filled.csv')
df_sorted = df_filled.sort_values(by=['Replicate','Treatment','EntryNumber'])
df_sorted = df_filled.drop(columns=['Treatment','Replicate','EntryNumber'])
df_sorted.to_csv('../results/phenos_rpkm_filled_sorted.csv', index=False)

In [14]:
# LAI列*1000，CCI列*10
df_sorted = pd.read_csv('../results/phenos_rpkm_filled_sorted.csv')
df_sorted['LAI'] = df_filled['LAI'] * 1000
df_sorted['CCI'] = df_filled['CCI'] * 10
df_sorted.to_csv('../results/phenos_rpkm_filled_sorted.csv', index=False)

In [15]:
df = pd.read_csv('../results/phenos_rpkm_filled_sorted.csv')

In [17]:
CCI = df.drop(columns=['DTF','FS','Fecundity','LAI'])
CCI.to_csv('../../dataProcessedResult/phenotype_rpkm/CCI.csv', index=False)

In [18]:
DTF = df.drop(columns=['CCI','FS','Fecundity','LAI'])
DTF.to_csv('../../dataProcessedResult/phenotype_rpkm/DTF.csv', index=False)

In [19]:
FS = df_filled.drop(columns=['DTF','CCI','Fecundity','LAI'])
FS.to_csv('../../dataProcessedResult/phenotype_rpkm/FS.csv', index=False)

In [20]:
LAI = df_filled.drop(columns=['DTF','FS','CCI','Fecundity'])
LAI.to_csv('../../dataProcessedResult/phenotype_rpkm/LAI.csv', index=False)

In [21]:
Fecundity = df_filled.drop(columns=['DTF','FS','CCI','LAI'])
Fecundity.to_csv('../../dataProcessedResult/phenotype_rpkm/Fecundity.csv', index=False)